[package]
name = "d20_combat_tracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "*"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
